language: go

go:
  - 1.3
  - 1.4

install:
  - go get golang.org/x/tools/cmd/cover
  - go get -v github.com/mattn/goveralls

script:
  - go test -cover ./... | sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''

after_success:
  - GOPATH=`pwd`:$GOPATH $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci