language: go

services:
  - elasticsearch

go:
  - 1.3
  - 1.4

install:
  - go get -t -v golang.org/x/tools/cmd/cover
  - go get -t -v -u github.com/golang/lint/golint
  - go get -t -v github.com/mattn/goveralls
  - go get -t -v ./...

before_script:
  - sleep 10
  - curl -XPUT localhost:9200/_template/tracker_visit -d'{"template":"tracker-test-*","mappings":{"visit":{"properties":{"_source":{"enabled":false},"_index":{"enabled":false},"_type":{"enabled":false},"_all":{"enabled":false},"_id":{"index":"not_analyzed","stored":true,"type":"string"},"@timestamp":{"format":"YYYY-MM-DD HH:mm:ss","type":"date"},"clientId":{"index":"not_analyzed","type":"string"},"dataList":{"include_in_parent":true,"type":"nested","properties":{"key":{"index":"not_analyzed","type":"string"},"value":{"index":"not_analyzed","type":"string"}}},"sessionId":{"index":"not_analyzed","type":"string"},"warnings":{"index":"not_analyzed","type":"string"}}}}}'
  - curl -XPUT localhost:9200/_template/tracker_event -d'{"template":"tracker-test","mappings":{"event":{"properties":{"_source":{"enabled":false},"_index":{"enabled":false},"_type":{"enabled":false},"_all":{"enabled":false},"_id":{"index":"not_analyzed","stored":true,"type":"string"},"enabled":{"type":"boolean"},"dataList":{"include_in_parent":true,"type":"nested","properties":{"key":{"index":"not_analyzed","type":"string"},"value":{"index":"not_analyzed","type":"string"}}},"filterList":{"include_in_parent":true,"type":"nested","properties":{"key":{"index":"not_analyzed","type":"string"},"value":{"index":"not_analyzed","type":"string"}}}}}}}'

script:
  - bash ./.test.sh

after_success:
  - GOPATH=`pwd`:$GOPATH $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  - cd $HOME/gopath/src/github.com/index0h/go-tracker
  - gofmt -e -l ./
  - golint ./... | grep -v 'comment'